version: '3'
services:
  frontend:
    image: nginx:latest
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  backend:
    image: 471112965581.dkr.ecr.eu-north-1.amazonaws.com/jayaraman_g:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
