name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # You can change this to the Node.js version you are using

    - name: Install dependencies
      run: npm install  --prefix  ./nodejs

    - name: Build Docker image
      run: |
        docker build -t jayaraman_g ./nodejs
        docker tag jayaraman_g:latest 471112965581.dkr.ecr.eu-north-1.amazonaws.com/jayaraman_g:latest

    - name: Log in to AWS ECR
      run: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 471112965581.dkr.ecr.eu-north-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1

    - name: Push image to ECR
      run: docker push 471112965581.dkr.ecr.eu-north-1.amazonaws.com/jayaraman_g:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1
